### PR TITLE
Use same spring context in verticles instances

### PR DESCRIPTION
**Pull request by inaiat**
I need share same Spring Application Context in verticles instances.

### CODE REVIEW

**Comment by JacpFX** [comment]
Hi, I am not quite sure if it is a good idea to have a shared context?! The current solution may have a slight overhead but you won't get any synchronization issues. I will take a look on this when I'm back from vacations.... THX Andy

**Comment by inaiat** [comment]
Hi, i thought about this... Can you explain about synchronization problem
later!
Thanks in advance!

Inaiat.

**Comment by amoAHCP** [comment]
Hi Inaiat,
first of all thank you for your work... and a happy new year :-) ...
Here are my thought about a shared Spring context in Vert.x:

1.) I don't see any sync problems in Spring itself
2.) Vert.x itself works by default on one EventLoop Thread, if you say -instances N ... you get N Threads for your N verticles... since you do not have any shared data (except the shared collections) you do not have to synchronizes anything... which makes it easy to code, debug,... and fast ;-)
3.) the default scope of a Spring bean is "singleton"... so in the current implementation you would have N "singleton beans" for N instances (verticles) .... which has a slight memory (and startup) overhead but still you do not need to synchronize anything.
4.) If I would apply your patch it may break many implementations, since now your "singleton bean" is really singleton an you now must synchronize the shared data access....
5.) have you tested your solution if you use classloader isolation?

So the question is why a shared context is needed?

1.) to share data between your instances? --> if so, this may be a bad idea... use vertx.sharedData instead   
2.) to reduce overhead and footprint of your veticles? OK this is a reason, but than it should be configureable.

Possible solution:
by default I prefer a non shared context, but a configureable solution with a flag to use shared context would be fine... this would not break any current implementations and would allow developers to choose (and they hopefully new what they are doing ;-) )

what do you think?

Andy

**Comment by inaiat** [comment]
Hi Andy,

Happy new Year :D

I agree with you about share context. It's better use vertx.sharedDate to
shared between instances of verticles. Forgot my idea about shared
Application Context.

But I wish a capability to pass my ApplicationContext to Vertx, because,
sometimes, I need custom configuration in Spring Context. I know that is a
problem for multiple instances of verticle (we can lock for this?). I don't
know if exist other possibible solution to pass ApplicationContext wihtout
static method.

Thanks!!!

**Comment by amoAHCP** [comment]
Hi, isn't it enough to do (@Autowired private ApplicationContext applicationContext;) your custom configuration should be always the same.

Andy

**Pull request closed without merging**
